# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 448599f60325ecd2b76603fdbd7e8d438604db25ebb6097077dc806df343f73389e39a3d3fd8c4267d037b46daa8414335d5cf7501473a0fce9a15896a301513

test:
  secret_key_base: a2be1b05fd00afadf0454943bd5d76c6187f8850d5cbc6f9f133f790b6e2e9efccb12a5564b2239f972bf1f8198f5de83081841ff20774eeb44e36f72b8679f3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
