require 'rails_helper'

describe AdminsController, :type => :controller do
  describe "GET index" do
    it "shows all admins" do
      admins = create_list(:admin, 2)
      get :index, format: :json
      data = JSON.parse(response.body)
      expect(data).not_to be_empty
      expect(data['admins'].first['fname']).to eq admins.first.fname
    end
  end

  describe 'GET #show' do
    before {@admin = create(:admin)}

    it "shows an admin" do
      get :show, id: @admin.id, format: :json
#      byebug
      data = JSON.parse(response.body)
      expect(data).not_to be_empty
      expect(data['admin']).to have_key('fname')
      expect(data['admin']['fname']).to eq @admin.fname
    end
    #
    # it "renders only in json" do
    #   expect{ get(:show, id: @cat.id, format: :html) }.to raise_error ActionController::UnknownFormat
    #   expect{ get(:show, id: @cat.id, format: :xml) }.to raise_error ActionController::UnknownFormat
    # end
    #
    # it "serves image_url generated by rabl" do
    #   url =  @cat.image.url
    #   expect(url).to_not be_nil
    # end

    # describe 'POST #create' do
    #   before {@user_attributes = attributes_for(:user)}
    #   it 'succeeds when all attributes are set' do
    #   #
    #   end

    #
    #     it 'fails when a required field is missing' do
    #     #
    #     end
    #   end
    #
    #   describe 'PATCH #update' do
    #     before {@user = create(:user)}
    #     it 'succeeds when valid data are changed' do
    #     #
    #     end
    #
    #     it 'fails when valid data are changed' do
    #     #
    #     end
    #   end
    #
    #   it 'DELETE #destroy' do
    #   #
    #   end
  end
end
